name = "JuliaSkriptumKontrolle"
uuid = "e7d8a85d-98e7-4e58-bbcb-2b33d0f590e8"
authors = ["Sebastian Pech <sebastian.pech@me.com>"]
version = "0.1.0"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra"]
